name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.5=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=pyha770c72_1
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - chardet=5.2.0=py311h38be061_2
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.1.0=py311h38be061_0
  - conda-build=25.1.1=py311h38be061_2
  - conda-index=0.5.0=pyhd8ed1ab_0
  - conda-libmamba-solver=25.1.1=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hf52228f_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.17.0=pyhd8ed1ab_0
  - fmt=11.0.2=h434a139_0
  - frozendict=2.4.6=py311h9ecbd09_0
  - h2=4.1.0=pyhd8ed1ab_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libarchive=3.7.7=h4585015_3
  - libblas=3.9.0=28_h59b9bed_openblas
  - libcblas=3.9.0=28_he106b2a_openblas
  - libcurl=8.11.1=h332b0f4_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - liblief=0.14.1=h5888daf_2
  - liblzma=5.6.3=hb9d3cd8_1
  - libmamba=2.0.5=h49b8a8d_1
  - libmambapy=2.0.5=py311hb3373dd_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.48.0=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=2.0.5=h8871ed4_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - menuinst=2.2.0=py311h38be061_0
  - more-itertools=10.6.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_2
  - nlohmann_json=3.11.3=he02047a_1
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_2
  - pkginfo=1.12.0=pyhd8ed1ab_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=6.1.1=py311h9ecbd09_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-lief=0.14.1=py311hfdbb021_2
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h9ecbd09_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_1_cpython
  - python-libarchive-c=5.1=py311h38be061_1
  - python_abi=3.11=5_cp311
  - pytz=2024.2=pyhd8ed1ab_1
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - readline=8.2=h8228510_1
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rhash=1.4.5=hb9d3cd8_0
  - ripgrep=14.1.1=h8fae777_0
  - rpds-py=0.22.3=py311h9e33e62_0
  - ruamel.yaml=0.18.10=py311h9ecbd09_0
  - ruamel.yaml.clib=0.2.8=py311h9ecbd09_1
  - setuptools=75.8.0=pyhff2d567_0
  - simdjson=3.11.6=h84d6215_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.15.0=h10c9db5_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.0=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - ase==3.26.0
      - ase-db-backends==0.10.0
      - astunparse==1.6.3
      - captum==0.8.0
      - cloudpickle==3.1.1
      - clusterscope==0.0.11
      - cmake==3.31.4
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - dgl==2.5.0+cu124
      - dgllife==0.3.2
      - dnspython==2.7.0
      - e3nn==0.5.7
      - easydict==1.13
      - expecttest==0.3.0
      - fairchem-core==2.4.0
      - fastapi==0.124.4
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - hypothesis==6.124.7
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lintrunner==0.12.7
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - markdown==3.9
      - matplotlib==3.10.6
      - molvs==0.1.1
      - monty==2025.3.3
      - mpmath==1.3.0
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - optree==0.14.0
      - orjson==3.11.3
      - pandas==2.3.2
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - psycopg2-binary==2.9.10
      - py4j==0.10.9.9
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyg-lib==0.4.0+pt26cu124
      - pymysql==1.1.2
      - pynndescent==0.5.13
      - pyod==2.0.5
      - pyparsing==3.2.3
      - pyre-extensions==0.0.32
      - python-dateutil==2.9.0.post0
      - python-etcd==0.4.5
      - python-multipart==0.0.20
      - rdkit==2025.3.6
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - sentry-sdk==2.37.0
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - starlette==0.50.0
      - submitit==1.5.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu124
      - torch-cluster==1.6.3+pt26cu124
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt26cu124
      - torch-sparse==0.6.18+pt26cu124
      - torch-spline-conv==1.2.2+pt26cu124
      - torchaudio==2.6.0+cu124
      - torchelastic==0.2.2
      - torchtnt==0.2.4
      - torchvision==0.21.0+cu124
      - triton==3.2.0
      - types-dataclasses==0.6.6
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - unimol-tools==0.1.5
      - uvicorn==0.38.0
      - wandb==0.21.3
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xgboost==3.1.2
      - yarl==1.20.1
prefix: /opt/conda
